### PR TITLE
Add dvc vscode extension asset

### PR DESCRIPTION
**Pull request by arcticbear**
The purpose of this PR is to add the DVC VSCode extension logo asset.
(The part of https://github.com/iterative/studio/issues/3767)

Example:
image

### CODE REVIEW

**Review by julieg18 — COMMENTED** [review]
Has this asset already been discussed and approved? I'm not sure if using the logo this way is legal 🤔

**Comment by arcticbear** [comment]
> Has this asset already been discussed and approved? I'm not sure if using the logo this way is legal 🤔

@julieg18 Yeah, you're right. This is from VS Code logo guidelines:

image

**Comment by casperdcl** [comment]
Alternatively how about just a generic "writing code" :memo: icon for now if needed for site banners? /CC @shcheklein

**Comment by maxagin** [comment]
"Things we are not OK with" was taken into the consideration. However, and because other big companies doing the same with the VS Code logo even in the market place we have decided to come up with the following option below, which to my mind is the same as the proposal above.

Screen Shot 2022-06-17 at 8 30 39 PM

**Pull request closed without merging**
