### PR TITLE
Create vscode.svg

### PR DESCRIPTION
**Pull request by arcticbear**
Based on https://github.com/iterative/studio/issues/3767

According to this [request](https://iterativeai.slack.com/archives/C01APS0FHDM/p1655432466990649) and [discussion](https://iterativeai.slack.com/archives/C01APS0FHDM/p1655491588656669?thread_ts=1655432466.990649&cid=C01APS0FHDM) from Slack, we need VS Code logo for showing DVC extension on the websites.

### CODE REVIEW

**Comment by arcticbear** [comment]
Any objections to merging it?

**Comment by casperdcl** [comment]
Unclear whether there was a decision in those threads so idk.
/CC @scheklein

**Comment by arcticbear** [comment]
> Unclear whether there was a decision in those threads so idk.
> /CC @shcheklein

@casperdcl Ivan has confirmed to use it [here](https://iterativeai.slack.com/archives/C01APS0FHDM/p1655491588656669?thread_ts=1655432466.990649&cid=C01APS0FHDM).

**Review by shcheklein — APPROVED** [review]

**Comment by shcheklein** [comment]
@arcticbear I've merged it. I'm not sure why Studio relies on GitHub to serve the assets though. E.g. it won't be "self-sufficient" when you run it on-prem. Not sure it's a good idea.

**Comment by arcticbear** [comment]
@shcheklein Thanks for merging this one. 
There are some items in the header using logos from this repository such as the products list. I think it may be related to the previous task of making headers and footers universal across all the iterative websites. But on-prem is a good point. I’ll discuss that with the Studio front-end team separately.

**Pull request merged**
